### ISSUE TITLE
Sharing the site on Slack shows React code rather that a nice site descriptions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/monorepo#10]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Possibly a bug in docusaurus

<img width="687" alt="image" src="https://user-images.githubusercontent.com/10214025/72977866-4ff3d480-3e10-11ea-8db6-a456d76b1b16.png">

**Comment by awalias** [comment]
![image](https://user-images.githubusercontent.com/458736/73148691-97bc7980-40f8-11ea-8bfe-96a7c432414f.png)

looks like you need to include the description markdown attribute on each page, otherwise it just takes the first line of text which in this case is some imports

**Comment by awalias** [comment]
I think for now lets just add descriptions, docusaurus probably needs a better way to guestimate the description from the content

**Comment by kiwicopple** [comment]
good idea. Not sure if possible, but it would be ideal if we could have this setup on every page:

```
---
id: get
title: 'Reading'
description: 'How to read records from your database.'
---
<p>{props.description}</p>

```
