### ISSUE TITLE
rpc() is not implemented

### ISSUE THREAD

**Issue by kiwicopple** [supabase/monorepo#11]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

@dragarcia I just want to check if you implemented the `rpc` function in `supabase-js`? I can't find it in any of the branches?

**Comment by dragarcia** [comment]
My bad, I missed out on that one. Let me do it next.

**Comment by kiwicopple** [comment]
Not started though right? Not to worry, I can do tomorrow, just want to make sure we don't double up
