### ISSUE TITLE
.like() & .ilike() does not work with '%'

### ISSUE THREAD

**Issue by dragarcia** [supabase/monorepo#12]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When passing a string pattern with the percentage sign (%) to the function .like() or .ilike(), the expected output is not attained.

* **Other information**  
According to the [PostgREST documentation](http://postgrest.org/en/v6.0/api.html#operators), the percentage sign (%) should be replaced with an asterisk (*) instead.

**Comment by kiwicopple** [comment]
@dragarcia perhaps we should just update the docs to use "*" instead? Always better to write less code

**Comment by dragarcia** [comment]
Possible as well, my consideration was that the norm for string patterns in pgsql were "%" and "_" (which works as per normal). Thought that it would be less confusing for the user to just stick to it.

**Comment by syna222** [comment]
Hi, I'm glad I found this entry because this seems to be a problem still (or again?) with Python Client (it works in JavaScript, though). Although the docs say it should be done with % this throws an error that can only be fixed by using *.
