### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by ric2b** [supabase/monorepo#13]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

I'm not sure what license this project is under, could you add it to the repo, please?
Looks really interesting though!

**Comment by ric2b** [comment]
I guess it's Apache 2 but this isn't very official looking: https://github.com/supabase/monorepo/issues/2

**Comment by kiwicopple** [comment]
Yes you're right @ric2b - it's Apache2. Added a License file to make more official. 

Hope you find the code helpful 👍
