### ISSUE TITLE
supabase-dev docker image doesn't work on Firefox

### ISSUE THREAD

**Issue by kiwicopple** [supabase/monorepo#16]
Testing:

- [x] Chrome: working
- [x] Safari: working
- [x] Firefox 72 - Not working
- [x] Firefox Dev - Not working
- [x] Firefox Alpha - Not working
- [x] Firefox 65 - Not working
- [x] Firefox 72: connecting to remote IP - Working
- [x] Firefox 72: connecting to local IP - not working
- [x] Firefox 72: connecting to local computer using named host - not working
- [ ] Firefox - docker-compose - TBD

**Comment by kiwicopple** [comment]
Possible causes:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1187666
- https://bugzilla.mozilla.org/show_bug.cgi?id=1376309
- https://bugzilla.mozilla.org/show_bug.cgi?id=1602502

**Comment by awalias** [comment]
same problem identified here: https://github.com/pocoproject/poco/issues/110

**Comment by kiwicopple** [comment]
And possibly resolved here: https://github.com/Kong/kong/pull/5495

**Comment by kiwicopple** [comment]
Solved by @awalias by using the nightly Kong release

**Comment by awalias** [comment]
we've now moved from nightly to Kong 2.0.1, as the fix is now in the official release
