### ISSUE TITLE
Reading data returns Promise instead of response

### ISSUE THREAD

**Issue by phamhieu** [supabase/monorepo#9]
* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When I read data from supabase, it returns a Promise instead of response array.

```
const getArtworks = async () => {
    try {
      let artworks = await supabase.from('artworks').select('*')
      return artworks
    } catch (error) {
      console.log('Error: ', error)
    }
  }
```

**Comment by awalias** [comment]
@kiwicopple is this intended? If so maybe we should update the examples on homepage to show console logging the result

**Comment by kiwicopple** [comment]
Nope, not intended. It should return the data. Let me check

**Comment by kiwicopple** [comment]
OK looks like just a bit of massaging of the code. Here is a simple React example:

```js
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient('URL', 'KEY')

const Index = () => {
  const [artworks, setArtworks] = useState([])

  /**
   * getArtworks
   */
  const getArtworks = async () => {
    try {
      let res = await supabase.from('artworks').select('*')
      setArtworks(res.body)
    } catch (error) {
      console.log('error', error)
    }
  }

  useEffect(() => {
    try {
      getArtworks()
    } catch (error) {
      console.log('Error: ', error)
    }
  }, [])

  return (
    <div>
      <pre>
        <code>{JSON.stringify(artworks, null, 2)}</code>
      </pre>
    </div>
  )
}
export default Index

```

It looks like we have 2 actions:

- Update the docs to make it clearer (probably put a section with ReactJS examples)
- Update the "Example responses" - they actually have a format like this (since the library wraps superagent):

```
body: []
status: 200
statusCode: 200
statusText: "OK"
```

**Comment by kiwicopple** [comment]
Closing this with the latest commit. There is still need for a react example but this can be covered in a full tutorial.

thanks for testing @phamhieu
